DROP TABLE area;
CREATE TABLE area (id_area int NOT NULL, nombreArea varchar(30), PRIMARY KEY (id_area)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
DROP TABLE cuenta;
CREATE TABLE cuenta (idCuenta int NOT NULL, clave varchar(25) NOT NULL, usuario int, nombreUsuario int NOT NULL, PRIMARY KEY (idCuenta), INDEX cuentaUsuarios_fk1 (usuario)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
DROP TABLE cuenta_prestamo;
CREATE TABLE cuenta_prestamo (idCuentaPrestamo int NOT NULL, idCuenta int NOT NULL, idPrestamo int NOT NULL, PRIMARY KEY (idCuentaPrestamo), INDEX cuenta_prestamo_fk1 (idCuenta), INDEX cuenta_prestamo_fk2 (idPrestamo)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
DROP TABLE estado;
CREATE TABLE estado (idEstado int DEFAULT '0' NOT NULL, nombreEstado varchar(25), PRIMARY KEY (idEstado)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
DROP TABLE libro;
CREATE TABLE libro (codigoRegistro int NOT NULL, tituloLibro varchar(25) NOT NULL, isbn varchar(25) NOT NULL, autor varchar(15) NOT NULL, editorial varchar(15) NOT NULL, descripcion varchar(150) NOT NULL, area int NOT NULL, estado int NOT NULL, agno int, idLibro int NOT NULL, PRIMARY KEY (idLibro), INDEX libro_fk1 (area), INDEX libro_estado_fk2 (estado)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
DROP TABLE prestamo;
CREATE TABLE prestamo (idPrestamo int NOT NULL, fechaPrestamo date NOT NULL, libro int NOT NULL, PRIMARY KEY (idPrestamo), INDEX prestamo_fk1 (libro)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
DROP TABLE tipo_usuario;
CREATE TABLE tipo_usuario (idTUsuario int NOT NULL, tipoNombre varchar(25) NOT NULL, PRIMARY KEY (idTUsuario)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
DROP TABLE usuario;
CREATE TABLE usuario (rut int NOT NULL, nombreUsuario varchar(25) NOT NULL, apellido1 varchar(25) NOT NULL, apellido2 varchar(25) NOT NULL, direccion varchar(30), fono int, email varchar(30), idTUsuario int NOT NULL, dVerificador varchar(10) NOT NULL, idUsuario int NOT NULL, PRIMARY KEY (idUsuario), INDEX usuario_fk1 (idTUsuario)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
ALTER TABLE cuenta ADD CONSTRAINT cuentaUsuarios_fk1 FOREIGN KEY (usuario) REFERENCES usuario (idUsuario);
ALTER TABLE cuenta_prestamo ADD CONSTRAINT cuenta_prestamo_fk1 FOREIGN KEY (idCuenta) REFERENCES cuenta (idCuenta) ;
ALTER TABLE cuenta_prestamo ADD CONSTRAINT cuenta_prestamo_fk2 FOREIGN KEY (idPrestamo) REFERENCES prestamo (idPrestamo);
ALTER TABLE libro ADD CONSTRAINT libro_area_fk2 FOREIGN KEY (area) REFERENCES area (id_area) ;
ALTER TABLE libro ADD CONSTRAINT libro_estado_fk2 FOREIGN KEY (estado) REFERENCES estado (idEstado);
ALTER TABLE prestamo ADD CONSTRAINT prestamo_Libro_fk1 FOREIGN KEY (libro) REFERENCES libro (idLibro);
ALTER TABLE usuario ADD CONSTRAINT usuario_fk1 FOREIGN KEY (idTUsuario) REFERENCES tipo_usuario (idTUsuario) ON UPDATE CASCADE;
